const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO:'DEC_METODO',
    MAIN: 'MAIN',
    
    IF: 'IF',
    IFCE:"IFCE",
    ELSEIF:"ELSEIF",
    IFCEIF:"IFCEIF",

    SWITCH: 'SWITCH',
    CASE: 'CASE',
    DEFAULT: 'DEFAULT',

    WHILE: 'WHILE',
    DOWHILE: 'DOWHILE',
    FOR: 'FOR',

    INCREMENTO: 'INCREMENTO',
    BREAK: 'BREAK',

    
    CONTINUE: 'INST_CONTINUE',
    RETURN: 'INST_RETURN',

    LLAMADA: 'INST_LLAMADA',
    ARREGLO: 'INST_ARREGLO',
    ACCESO_ARREGLO: 'INST_ACCESO_ARREGLO',
    TOLOWER: 'INST_TOLOWER',
}
module.exports = TIPO_INSTRUCCION;