const TIPO_OPERACION={
    SUMA:'SUMA',
    RESTA:'RESTA',
    MULTIPLICACION: 'MULTIPLICACION',
    DIVISION: 'DIVISION',
    POTENCIA: 'POTENCIA',
    MODULO:'MODULO',
    UNARIA:'UNARIA',
    NEGACION:'NEGACION',
    IGUALIGUAL:'IGUALIGUAL',
    DIFERENTE:'DIFERENTE',
    MENOR: 'MENOR',
    MENORIGUAL:'MENORIGUAL',
    MAYOR:'MAYOR',
    MAYORIGUAL:'MAYORIGUAL',
    OR:'OR',
    AND:'AND',
    NOT:'NOT'
}
module.exports=TIPO_OPERACION;

// const TIPO_INSTRUCCION = {
//     SUMA: 'SUMA',
//     RESTA: 'RESTA',
//     MULTIPLICACION: 'MULTIPLICACION',
//     DIVISION: 'DIVISION',
//     POTENCIA: 'POTENCIA',
//     MODULO: 'MODULO',
//     UNARIA: 'UNARIA',
//     NEGACION: 'NEGACION',
//     IGUALDAD: 'IGUALDAD',
//     DIFERENTE: 'DIFERENTE',
//     MENOR: 'MENOR',
//     MAYOR: 'MAYOR',
//     MENOR_IGUAL: 'MENOR_IGUAL',
//     MAYOR_IGUAL: 'MAYOR_IGUAL',
//     AND: 'AND',
//     OR: 'OR',
//     NOT: 'NOT',
// }

// module.exports= TIPO_INSTRUCCION;