const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO:'DEC_METODO',
    MAIN: 'MAIN',
    IF: 'IF', //ULTIMO AGREGADO
    ELSE: 'ELSE',
    ELSEIF: 'INST_ELSEIF',
    WHILE: 'INST_WHILE',
    DO_WHILE: 'INST_DO_WHILE',
    FOR: 'INST_FOR',
    SWITCH: 'INST_SWITCH',
    CASE: 'INST_CASE',
    DEFAULT: 'INST_DEFAULT',
    BREAK: 'INST_BREAK',
    CONTINUE: 'INST_CONTINUE',
    RETURN: 'INST_RETURN',
    LLAMADA: 'INST_LLAMADA',
    ARREGLO: 'INST_ARREGLO',
    ACCESO_ARREGLO: 'INST_ACCESO_ARREGLO',
    TOLOWER: 'INST_TOLOWER',
}
module.exports = TIPO_INSTRUCCION;
