const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO:'DEC_METODO',
    DEC_FUNCION: 'DEC_FUNCION',
    MAIN: 'MAIN',
    LLAMADA_METODO: 'LLAMADA_METODO',
    LLAMADA_FUNCION: 'LLAMADA_FUNCION',
    
    IF: 'IF',
    IFCE:"IFCE",
    ELSEIF:"ELSEIF",
    IFCEIF:"IFCEIF",

    SWITCH: 'SWITCH',
    CASE: 'CASE',
    DEFAULT: 'DEFAULT',

    WHILE: 'WHILE',
    DOWHILE: 'DOWHILE',
    
    
    FOR: 'FOR',

    BREAK: 'BREAK',
    INCREMENTO: 'INCREMENTO',
    DECREMENTO: 'DECREMENTO',


    
}
module.exports = TIPO_INSTRUCCION;